### ISSUE TITLE
Running original IS10_paraling config

### ISSUE THREAD

**Issue by ATriantafyllopoulos** [audeering/opensmile-python#109]
Currently, the `opensmile-python` wrapper supports only [a limited set](https://audeering.github.io/opensmile-python/api/opensmile.FeatureSet.html) of the [original cofings](https://github.com/audeering/opensmile/tree/master/config). I have been trying to use the configs of the [ComParE challenges](https://github.com/audeering/opensmile/tree/master/config/is09-13).

In general, it seems that one needs to substitute the "old" [input]((https://github.com/audeering/opensmile/blob/341aea9ce52bc63d7fe75098027a394994f8493b/config/is09-13/IS09_emotion.conf#L32))/[output](https://github.com/audeering/opensmile/blob/341aea9ce52bc63d7fe75098027a394994f8493b/config/is09-13/IS09_emotion.conf#L62) configs with the newer format ([input](https://github.com/audeering/opensmile-python/blob/a4c5e965448c3c3776762344f53337d481068a89/opensmile/core/config/egemaps/v02/eGeMAPSv02.conf#L16)/[output](https://github.com/audeering/opensmile-python/blob/a4c5e965448c3c3776762344f53337d481068a89/opensmile/core/config/egemaps/v02/eGeMAPSv02.conf#L36)) supported in the `opensmile-wrapper`

Essentially, this boils down to substituting:

+ `\{../shared/standard_wave_input.conf.inc}` with `\{\cm[source{?}:include external source]}`
+ `\{../shared/standard_data_output.conf.inc}` with `\{\cm[sink{?}:include external sink]}`

This works fine with the following configs: `{IS09_emotion, IS11_speaker_state, IS12_speaker_trait, IS13_ComParE.conf}`.

However, when I try it on `IS10_paraling`, I get `opensmile.core.lib.OpenSmileException: Code: 4, Message: specified component does not exist`. The only `ERR` messages in the `logfile` are:
+ `(ERR) [0] commandlineParser: parse: unknown option '-sink' on commandline!`
+ `(ERR) [0] commandlineParser: parse: unknown option '-sinkLevel' on commandline!`

However, the other configs also sometimes show errors without failing to initialize the `smile_api`. Is there anything particular I should pay attention to for this config?

**Comment by hagenw** [comment]
@ureichel @maxschmitt does anybody of you have experience how to adapt configs to work with our Python version of `opensmile`?

**Comment by maxschmitt** [comment]
@ATriantafyllopoulos 
For me, also the `IS10_paraling` works, when adapting it in exactly the same way as you described for `IS09_emotion`.

**Comment by maxschmitt** [comment]
How do you come across version `v3.27.4` of openSMILE? I was not aware that a version like this exists (latest official release is `3.0.2`).

Anyway, the fact that `-sink` is not found seems to be the main issue for now. Could it be that there is some conflicting installation of openSMILE? (You are working on Ubuntu, right?)

Could you also send me the modified config file for `IS10_paraling` to ensure that we are on the same page?

**Comment by ATriantafyllopoulos** [comment]
You are right about the C++ version, I have `v3.0.2-1-g341aea9`, the other number came from my shell, which shows versions for stuff, but apparently got it wrong.

But that is for the code which I use to reference my configs (i.e. what I cloned locally), the binary packaged with the python wrapper (`v2.5.0`) is `v3.0.1`.  However, you are also using the same setup as I am.

Attaching my config: [IS10_paraling.zip](https://github.com/user-attachments/files/16346490/IS10_paraling.zip)

**Comment by maxschmitt** [comment]
Sorry, I meant the modified config file for the feature set, not the package.

**Comment by ATriantafyllopoulos** [comment]
A misclick, sorry! Here's the correct zip

[IS10_paraling.zip](https://github.com/user-attachments/files/16346730/IS10_paraling.zip)

**Comment by maxschmitt** [comment]
It seems option name is `\{\cm[source{?}:include external sink]}` again in line `59`, but it should be `\{\cm[sink{?}:include external sink]}`.

After changing that, it is working fine for me.

**Comment by ATriantafyllopoulos** [comment]
Ah, I'm an idiot. Of course. Sorry, copy-pasting sometimes get you..it works now!
