### ISSUE TITLE
How can I customize parameters

### ISSUE THREAD

**Issue by vuongvantinh** [audeering/opensmile-python#16]
How can I change `frameSize `and `frameStep ` when extracting features? Adding `options ` (change `frameSize `from `0.025 -> 0.03` and `frameStep `from `0.01 -> 0.015` ) did not work for me.
```
    smile = opensmile.Smile(
            feature_set=opensmile.FeatureSet.eGeMAPSv01b,
            feature_level=opensmile.FeatureLevel.Functionals,
            options={"frameMode": "fixed", "frameSize": 0.03, "frameStep": 0.015}
        )

    y = smile.process_signal(signal, sample_rate)
```
It generate the same features as by the default parameters.

**Comment by frankenjoe** [comment]
Currently, `frameSize` and `frameStep` are not configurable. 

What you could try is changing this in the script by changing e.g.:

```
frameSize = 0.020
```

to 

```
frameSize = \cm[frameSize{0.020}:frame size in seconds]
```

However, you probably have to change it in several places to avoid period mismatch errors across levels.

Btw: you will find the scripts of the standard features sets in a folder `opensmile/core/config`.
