### ISSUE TITLE
SoX could not be found!

### ISSUE THREAD

**Issue by aceprojectx** [audeering/opensmile-python#21]
SoX could not be found!

    If you do not have SoX, proceed here:
     - - - http://sox.sourceforge.net/ - - -

    If you do (or think that you should) have SoX, double-check your
    path variables.

What's SoX doing in this project ? 
Should i need to install,  How to install ? is pip install sox ? or install on windows ?
Thank you for your work , it's goo for me !

**Comment by hagenw** [comment]
We are using `audiofile` to read sound files in `opensmile`.
If you try to read a non WAV or FLAC file with `audiofile` it might require other programs like sox or ffmpeg, see https://audeering.github.io/audiofile/installation.html

Which means in your case something like:
```bash
$ sudo apt-get install sox
```
should fix the problem. Or you can first use another program to convert your files to WAV.
