### ISSUE TITLE
version and feature level

### ISSUE THREAD

**Issue by istyle0526** [audeering/opensmile-python#22]
Hi, Thank you for the awesome work here!!

Does this python package correspond to the v2.0.0 of the C release?
If so, can I get the list of feature sets that are not included in the python version yet? (And the number of them if possible)

And, I'd like to know what does each level of the feature mean. (LDD, delta, and functionals)

**Comment by hagenw** [comment]
The `opensmile` Python package correspond curently to version [3.0.0 of opensmile](https://github.com/audeering/opensmile/releases/tag/v3.0.0).

**Comment by istyle0526** [comment]
@hagenw Thanks, that helped!
