### ISSUE TITLE
Error message: OSError: libmvec.so.1: cannot open shared object file: No such file or directory when importing

### ISSUE THREAD

**Issue by henrypowell87** [audeering/opensmile-python#26]
Seems to be some dependency error when trying to import opensmile:

Complete error message:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user_name/.local/lib/python3.6/site-packages/opensmile/__init__.py", line 6, in <module>
    from opensmile.core.smile import (
  File "/home/user_name/.local/lib/python3.6/site-packages/opensmile/core/smile.py", line 13, in <module>
    from opensmile.core.SMILEapi import (
  File "/home/user_name/.local/lib/python3.6/site-packages/opensmile/core/SMILEapi.py", line 23, in <module>
    smileapi = cdll.LoadLibrary(smileapi_path)
  File "/usr/lib64/python3.6/ctypes/__init__.py", line 421, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib64/python3.6/ctypes/__init__.py", line 343, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libmvec.so.1: cannot open shared object file: No such file or directory`

Minimal code to reproduce on my system:

`import opensmile

smile = opensmile.Smile(
    feature_set=opensmile.FeatureSet.ComParE_2016,
    feature_level=opensmile.FeatureLevel.Functionals,
)`

System specs:

OS: Centos7-6 X86_64
Python 3.6.8
Code Running on PyCharm

Did a few searches and people are occasionally reporting a similar error in relation to FFMPEG although I could not find a good way of resolving the issue in that context.

**Comment by chausner-audeering** [comment]
The problem is that the native binaries that come included with the Python package have been built with recent versions of gcc and are not compatible with CentOS 7. We definitely need to state the OS compatibility more clearly in the README.

It might be possible to make it compatible by installing some non-default packages for CentOS but unfortunately I don't have any experience on that so can't give you specific instructions.

There is always the possibility of compiling openSMILE yourself on CentOS and including your self-built binary in opensmile-python.

**Comment by henrypowell87** [comment]
OK no problem. I'll have a look into building the binary from a seperate compilation. Thanks!

**Comment by ckarjadi** [comment]
I am also having this issue. Any sharing of a solution or advice how to compile and running opensmile on Centos 7 would be greatly appreciated. Not sure if @henrypowell87 has found a solution and would please be able to share.

Also, what are the compatible operating systems for opensmile? Are there other Linux operating systems that will work?

**Comment by henrypowell87** [comment]
I ended up just installing opensmile on a windows machine using anaconda.

**Comment by hagenw** [comment]
I created https://github.com/audeering/opensmile-python/issues/33 to track the issue of missing documentation for supported Linux distributions and gcc versions.

**Comment by harrygcoppock** [comment]
Hi, I am also facing this issue. Installing via
`pip install opensmile`
and 
`git clone https://github.com/audeering/opensmile-python.git
cd opensmile-python
python setup.py install`

did not work leading to the above error on
`import opensmile.py`

Any help would be greatly appreciated.
