### ISSUE TITLE
Minimum length to extract functionals

### ISSUE THREAD

**Issue by bagustris** [audeering/opensmile-python#30]
Hi there, 

I got an error while extracting a short audio file. The error said, 
`UserWarning: Segment too short, filling with NaN.
  UserWarning("Segment too short, filling with NaN.")`

My question is: what is the minimum length to extract acoustic features from an audio file?
My case was with Compare 2016 functionals.

I can't find it in the source code (egemaps config file).
Also better to show it in the documentation.

Afaik, for LLD is 25 ms for each frame.
But there is no information for minimum samples or 
duration for functionals in one utterance/audio file.

**Comment by chausner-audeering** [comment]
Good question, I don't think we have this documented anywhere at the moment.

The minimum length needed to compute functionals should be at least one LLD in the levels on which the functionals are computed on. For some feature sets, certain functionals are computed on delta LLDs so there the minimum length is probably two LLDs.
