### ISSUE TITLE
Resampling and remixing not working under Windows

### ISSUE THREAD

**Issue by hagenw** [audeering/opensmile-python#36]
As `audresample` does not work under Windows (https://github.com/audeering/audresample/pull/5), and we switched in #35 to it, `opensmile` will fail under Windows if user ask to resample or remix incoming audio signals.

**Comment by frankenjoe** [comment]
I think it will already fail when the user does:

```python
import opensmile
```

There's a note on top of the README that `2.1.0` is not compatible with Windows. But we need to provide a fix as soon as possible.

**Comment by frankenjoe** [comment]
Fixed with https://github.com/audeering/opensmile-python/pull/37
