### ISSUE TITLE
Emobase setup.py

### ISSUE THREAD

**Issue by FrogInABlender** [audeering/opensmile-python#38]
Hi all,

i have seen that the emobase feature set has been added in v.2.0.1.

However, i had to adapt the setup.py (adding the path to the config) in order to get it running.

Is this the intended behaviour?

Kind regards

Frog

**Comment by frankenjoe** [comment]
Thanks for reporting, will be fixed in https://github.com/audeering/opensmile-python/pull/39

**Comment by frankenjoe** [comment]
Issue was fixed with release `2.1.3`.
