### ISSUE TITLE
Add support for Apple M1 architecture

### ISSUE THREAD

**Issue by hagenw** [audeering/opensmile-python#78]
Similar to the approach we followed for `audresample` in https://github.com/audeering/audresample/pull/33 we should add binaries for M1 here. We can create an internal project that uses our internal M1 runner to check that all tests passes as we also do for `audresample` in the `audresample-ci` project.

/cc @Linux13524 @drux007 @frankenjoe

**Comment by hagenw** [comment]
See also https://github.com/audeering/opensmile-python/issues/64

**Comment by hendryman** [comment]
I would be absolutely enthusiastic and eternally grateful if this were to happen : )

**Comment by hagenw** [comment]
Good news, with the release 2.5.0 we now support the M1 architecture.
